name: ortto_flutter_sdk_platform_interface
description: Ortto Flutter SDK Platform Interface
version: 0.2.0
homepage: https://ortto.com/
repository: https://github.com/autopilot3/ortto-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
