name: ortto_flutter_sdk_example
description: Demonstrates how to use the ortto_flutter_sdk plugin.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  ortto_flutter_sdk: ^0.6.0
#  ortto_flutter_sdk:
#    path: ../ortto_flutter_sdk
  uuid: ^3.0.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
