name: ortto_flutter_sdk
description: Ortto Flutter SDK
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: ortto_flutter_sdk_android
      ios:
        default_package: ortto_flutter_sdk_ios

dependencies:
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  ortto_flutter_sdk_android:
    path: android
  ortto_flutter_sdk_ios:
    path: ios
  ortto_flutter_platform_interface:
    path: platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
