name: ortto_flutter_sdk_android
description: Android implementation of the ortto_flutter_sdk plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: ortto_flutter_sdk
    platforms:
      android:
        package: com.ortto.messaging.flutter
        pluginClass: FlutterOrttoPushSdkPlugin
        dartPluginClass: FlutterOrttoPushSdkAndroid

dependencies:
  flutter:
    sdk: flutter
  ortto_flutter_platform_interface:
    path: ../platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
