// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx-edTQU9ZFkZkWkiWcB9VMO6vgDogIVs',
    appId: '1:911842528456:android:38463ca249d14b667369fd',
    messagingSenderId: '911842528456',
    projectId: 'ortto-sdk-flutter-example',
    storageBucket: 'ortto-sdk-flutter-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCch05MqFlijNI5utP6QVDDW_LpJkK-0xQ',
    appId: '1:911842528456:ios:ebb5de222d0e2f007369fd',
    messagingSenderId: '911842528456',
    projectId: 'ortto-sdk-flutter-example',
    storageBucket: 'ortto-sdk-flutter-example.appspot.com',
    androidClientId: '911842528456-k1dtre43o6jafrf5mja0leutpdlgtkar.apps.googleusercontent.com',
    iosClientId: '911842528456-7h0sn3vbavblun191t1goo0va6le5bjg.apps.googleusercontent.com',
    iosBundleId: 'com.ortto.flutterdemo',
  );
}
