name: ortto_flutter_sdk
description: Ortto Flutter SDK
version: 0.6.2
homepage: https://ortto.com/
repository: https://github.com/autopilot3/ortto-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: ortto_flutter_sdk_android
      ios:
        default_package: ortto_flutter_sdk_ios

dependencies:
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  ortto_flutter_sdk_android: ^0.4.8
#  ortto_flutter_sdk_android:
#    path: ../ortto_flutter_sdk_android
  ortto_flutter_sdk_platform_interface: ^0.4.0
#  ortto_flutter_sdk_platform_interface:
#    path: ../ortto_flutter_sdk_platform_interface
  ortto_flutter_sdk_ios: ^0.6.2
#  ortto_flutter_sdk_ios:
#    path: ../ortto_flutter_sdk_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

topics:
  - communication
  - notifications
  - widgets
