name: Deploy SDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Reference (tag, commit)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  deploy-to-pub-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Deploy platform_interface
        run: |
          cd ortto_flutter_platform_interface
          flutter pub publish --dry-run 

      - name: Deploy sdk_ios
        run: | 
          cd ortto_flutter_sdk_ios 
          flutter pub publish --dry-run

      - name: Deploy sdk_android
        run: |
          cd ortto_flutter_sdk_android 
          flutter pub publish --dry-run 

      - name: Deploy sdk
        run: |
          cd ortto_flutter_sdk 
          flutter pub publish --dry-run
