name: Deploy SDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Reference (tag, commit)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  deploy-to-pub-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.0.2


      - name: Deploy platform_interface
        run: |
          cd ortto_flutter_sdk_platform_interface
          flutter pub get
          flutter pub publish --dry-run 

      - name: Deploy sdk_ios
        run: | 
          cd ortto_flutter_sdk_ios 
          dart pub publish --dry-run

      - name: Deploy sdk_android
        run: |
          cd ortto_flutter_sdk_android 
          dart pub publish --dry-run 

      - name: Deploy sdk
        run: |
          cd ortto_flutter_sdk 
          dart pub publish --dry-run
